### ISSUE TITLE
search line for applications at bottom

### ISSUE THREAD

**Issue by martiyanov** [BranchMetrics/sesame_issues#102]
Hello I need search line for applications at bottom.

**Comment by philwall2** [comment]
Can you explain this a bit more? I don't understand.

**Comment by martiyanov** [comment]
hi,
I mean, when i start sesame, my finger at the bottom of phone and will be
comfort for me to press "find app" at the bottom.

вт, 13 авг. 2019 г., 5:15 philwall2 <notifications@github.com>:

**Comment by philwall2** [comment]
Are you looking to flip the display so things show at the bottom? You can do that in Sesame Settings > Look & feel > Search look & feel > Show results from

If that's not what you mean could you explain in more detail? Perhaps a screenshot?

**Comment by martiyanov** [comment]
Hi,
No I mean "search applications" line, which is on to on screenshot in
previous my mail.

С уважением, Степан Мартьянов.
+7(920)016-04-80


ср, 14 авг. 2019 г. в 18:36, philwall2 <notifications@github.com>:

**Comment by martiyanov** [comment]
ups, sorry it's not your application ) it is nova

С уважением, Степан Мартьянов.
+7(920)016-04-80


ср, 14 авг. 2019 г. в 20:14, Степан <martiyanov@gmail.com>:
