### ISSUE TITLE
Search results are shown in Chrome, independent of the settings

### ISSUE THREAD

**Issue by ssdd28561** [BranchMetrics/sesame_issues#103]
I have Chrome and Chrome Canary installed. My default browser is Chrome Canary.
But as you see on the second screenshot, normal Chrome is on the first place in the quick search, and ot will be opened despite the settings on the first screenshot. There is no toggle to turn off for Chrome in settings. Disabling the normal Chrome in android settings brokes the Sesame - there will be an epmty space instead of normal Chrome icon, and the search will be opened in random app or the default browser opens without the search query.

Previously the search results were shown in google app, at it is supposed to happen with current order in settings, but in the recent updates something went wrong.

![Screenshot_20190813-191107](https://user-images.githubusercontent.com/8882800/62958234-f74ef300-bdfe-11e9-8c85-e14165c9fa76.png)
![Screenshot_20190813-191636](https://user-images.githubusercontent.com/8882800/62958248-fddd6a80-bdfe-11e9-86df-57680d6bec74.png)
![Screenshot_20190813-192333](https://user-images.githubusercontent.com/8882800/62958712-fa96ae80-bdff-11e9-83a0-aa6380082106.png)

**Comment by ssdd28561** [comment]
Sesame version 3.5.3-beta1
Android (Pixel 3xl) QPP6.190730.005
Lawnchair launcher version 2.0-2357-ci-alpha

**Comment by philwall2** [comment]
Good news. Steve can reproduce and knows how to fix it :)
Thanks for reporting!

**Comment by philwall2** [comment]
@ssdd28561 this should be fixed in the newest Beta (3.5.3 beta 3). Can you verify it's working now?

**Comment by ssdd28561** [comment]
Issue was fixed: Normal Chrome is visible in the quicksearch apps, could be disabled. I moved google app to the top of the list, and now search results are opened there after I press enter - so everything is perfect now 👍
