### ISSUE TITLE
Frequently used apps

### ISSUE THREAD

**Issue by TAHayden** [BranchMetrics/sesame_issues#108]
Could an option be added to allow the selection of most frequently used apps calculated by app usage to appear at the top of Sesame as opposed to the most recently used? Additionally, or alternatively could a user be allowed to pin apps there instead?

**Comment by philwall2** [comment]
Yep! We've got that on the roadmap #40 . FYI - we're going to be building new data features for a while. We've spent most of the last year on UI and want to get back to the stuff that makes us diffeerent.

**Comment by TAHayden** [comment]
Awesome, thanks.
