### ISSUE TITLE
No toast notifications with adguard anymore

### ISSUE THREAD

**Issue by d0x360** [BranchMetrics/sesame_issues#114]
I used to get a toast notification when I typed ad which brought up a shortcut to check for updates in the app adguard (adguard.com version) and then I would get a toast notification saying how many filters were updated 

After the last update of sesame that stopped.  Now I the update happens but I get no notification but If I run the update again I'll get a notification in a green bar at the bottom of the screen which says "no updates available"

I havent changed any settings in Sesame, Android or adguard.  I'm on a note 10+ running Android 9 with the August security update.

**Comment by philwall2** [comment]
Hi, I don't use adguard so I'm not 100% sure what you mean. But it sounds like 

- You were using an adguard shortcut from Sesame Search
- That shortcut would do some sort of check and respond with a toast
- It's no longer working

Is that right? If so, that would be an adguard shortcut that Sesame automatically detects and makes available. Which means the change would be from adguard. It's still possible we could find a way to make it work.

Could you send me a screenshot of 1) the bug, 2) the shortcut settings screen in Sesame for adguard (Sesame Settings > Shortcuts > Adguard).

FYI - there's probably nothing we can do, it sounds like an adguard change. But I'll take a look.

**Comment by d0x360** [comment]
Yes, the way you explained it is correct.  Fortunately you can close this
issue.

I was told by adguard support that nothing regarding notifications had
changed but then I went to their GitHub page and saw that something was
changed its just not finished yet so it's only throwing notifications for
certain events.

I planned on updating the post when I went on lunch.  I only found out the
system was being changed a couple hours ago.
