### ISSUE TITLE
Korean Translation Issue

### ISSUE THREAD

**Issue by adan89lion** [BranchMetrics/sesame_issues#116]
![Screenshot_20190926-121027587_1](https://user-images.githubusercontent.com/6585644/65657615-c5c66b80-dfe9-11e9-96bd-256480f2a8f9.jpg)
![Screenshot_20190926-121000431_1](https://user-images.githubusercontent.com/6585644/65657617-c5c66b80-dfe9-11e9-8f36-6e4e86e773ff.jpg)
There are two `설정` (Settings) in the app menu and bottom bar and often confuses me. I don't have a better translate suggestion but two items in the menu with the same name is really confusing.
Perhaps `설정` and `앱 설정` would be better?

**Comment by philwall2** [comment]
I don't speak Korean so I have no idea :(

We have a volunteer translation platform. If you speak Korean I'd be happy to add you.

**Comment by adan89lion** [comment]
> We have a volunteer translation platform. If you speak Korean I'd be happy to add you.

Thanks, that would be very helpful!

**Comment by philwall2** [comment]
@adan89lion what's your email? I'll send you access. Or you can email me for it: phil@sesame.ninja
