### ISSUE TITLE
Search support for YouTube Vanced

### ISSUE THREAD

**Issue by Apollucas** [BranchMetrics/sesame_issues#122]
So this might be a bit of a niche request;

I use an alternative (and in my opinion, better) YouTube app called YouTube Vanced. It's built upon the original YouTube app and it has some extra features that the original doesn't have, but that's not my point.

My issue is that it's not possible to use it as a search option like the original app. If this could be added in a future version, that'd be appreciated.

Great app, by the way. Keep up the good work :)

**Comment by philwall2** [comment]
Hi. Unfortunately we're not allowed to support Vanced. Google considers it a piracy app and has stated they could ban apps that associate with Vanced. Given Google's track record, that's a risk we can't take :)
