### ISSUE TITLE
Telegram two-step verification

### ISSUE THREAD

**Issue by kshatriya-abhay** [BranchMetrics/sesame_issues#126]
Telegram now has a two-step verification which asks for a password after the 'OTP' when we try to login.
The password screen doesn't show in Sesame's tg setup so login remains incomplete. Request to add support for that

**Comment by philwall2** [comment]
Hi Abhay, we looked into this before and Telegram's API doesn't support 2FA for 3rd party apps. You'll have to turn OFF 2FA, connect to Sesame, then turn it back on.

Sorry about that. If Telegram made it possible, we would implement the change.

**Comment by Jeff11** [comment]
It would help if the app would explain this. I wondered why it wasn't working.

**Comment by philwall2** [comment]
@Jeff11 good idea. I think the app does say "if you're having trouble try turning OFF two factor authentication". But we could make that more visible.
