### ISSUE TITLE
Screen edge overlay remains on screen

### ISSUE THREAD

**Issue by yochananmarqos** [BranchMetrics/sesame_issues#130]
After today's beta update, if I activate Screen Edge and tap outside the app shortcut area to dismiss it, the overlay stays on the screen and tapping anywhere launches Screen Edge again. If I launch an app, it behaves normally.

Sesame 3.6.0-beta6/build 14388
Android 9.0.0
Oxygen OS 9.5.11.GM31CB
T-Mobile OnePlus 7 Pro

**Comment by philwall2** [comment]
Hi, did you email me about this too? I can't reproduce this on my test devices so I want to understand if it's OxygenOS only users who are seeing it.

**Comment by exolon** [comment]
Same here, on a OnePlus 6 running Pie OB26. This behavior is fairly consistent.

**Comment by yochananmarqos** [comment]
@philwall2 No, I didn't send an email.

**Comment by yochananmarqos** [comment]
The issue is resolved with beta 7. Thanks!

**Comment by philwall2** [comment]
Thanks for reporting :)
