### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by Chaphasilor** [BranchMetrics/sesame_issues#131]
I read the announcement for contact actions today, and although I don't need the feature, I'd be interested in donating, maybe on a monthly basis, because I use sesame as my actual launcher and therefore hundreds of times per day.

Could you make this a thing? Maybe even as a voluntary in-app purchase (subscriptions are supportet as well afaik)?

Keep up the good work!

**Comment by Kordian-Dziwisz** [comment]
I'm also using it as my actual launcher. Try to contact them through email, It's only taking space on the issue board.

**Comment by Chaphasilor** [comment]
okay, will close the issue now...
