### ISSUE TITLE
Email/call/message icons don't show

### ISSUE THREAD

**Issue by Kordian-Dziwisz** [BranchMetrics/sesame_issues#141]
Rooted Samsung Galaxy S7 (lineage os) + open gapps + Google messages / contacts

Before root (Samsung messages/contacts app were installed) there were email/call/message icons on right side of contact when searching. Now I have shortcuts to message/call but no icons, which have been easier to use than additional shortcuts.

I suggest implementing email/call/message shortcuts to open gapps

![screenshot](https://i.imgur.com/sH6DguP.png)

**Comment by ghd182** [comment]
Yeah for me it's the same (also in app purchase for contact actions does nothing)

**Comment by philwall2** [comment]
Sorry about that. It's out fault. There's a bug in Contact Actions that we can't reproduce so we added some more debug data tracking to the Beta. 

You can [join the Beta here](https://play.google.com/apps/testing/ninja.sesame.app.edge  
). Then go to Sesame Settings, Settings, Debug data, and "TAP TO SEND DEBUG DATA TO THE DEVELOPERS". Include the message "Contact actions".

That will give us a chance to see the problem and work on a fix.

Sorry for the hassle. Thanks for reporting and helping.

**Comment by showdawn** [comment]
I am on a Galaxy note 10 plus (non rooted) and was enrolled in beta. All of a sudden the search stopped working ( literally the app would close ). After that I unenrolled from beta. The app search works now , but none of the  default phone  actions work. Like call , message etc. Infact they don't show up. 

If I use Nova search they show up, but clicking on phone shows a toast message. 

I uninstalled and reinstalled several times.

**Comment by showdawn** [comment]
> I am on a Galaxy note 10 plus (non rooted) and was enrolled in beta. All of a sudden the search stopped working ( literally the app would close ). After that I unenrolled from beta. The app search works now , but none of the default phone actions work. Like call , message etc. Infact they don't show up.
> 
> If I use Nova search they show up, but clicking on phone shows a toast message.
> 
> I uninstalled and reinstalled several times.

The newer beta version resolved it.
