### ISSUE TITLE
Contact actions add-on does nothing

### ISSUE THREAD

**Issue by ghd182** [BranchMetrics/sesame_issues#142]
I have purchased the contact actions add-on, but nothing is changed... I have multiple shortcuts for the same account (contact, whatsapp, dialer) and only the default 3 shortcuts for contact shortcuts, even if I disable them from settings.

Plus -> long pressing the default shortcuts they disappear

![Screenshot_2019-12-22-18-03-58-684_com teslacoilsw launcher](https://user-images.githubusercontent.com/9931444/71324930-88d51c80-24e5-11ea-88d6-429fae48f671.png)
![Screenshot_2019-12-22-18-04-20-400_com teslacoilsw launcher](https://user-images.githubusercontent.com/9931444/71324931-896db300-24e5-11ea-95a6-aa3f4bf91740.png)
![Screenshot_2019-12-22-18-04-16-405_com teslacoilsw launcher](https://user-images.githubusercontent.com/9931444/71324932-896db300-24e5-11ea-86b5-09ba353947c0.png)
![Screenshot_2019-12-22-18-03-44-218_ninja sesame app edge](https://user-images.githubusercontent.com/9931444/71324933-896db300-24e5-11ea-95b5-76f63c7ea8b2.png)
![Screenshot_2019-12-22-18-04-25-146_com teslacoilsw launcher](https://user-images.githubusercontent.com/9931444/71324934-8a064980-24e5-11ea-9935-7042cf87c7ce.png)

**Comment by philwall2** [comment]
Sorry about that. It's out fault. There's a bug in Contact Actions that we can't reproduce so we added some more debug data tracking to the Beta. 

You can [join the Beta here](https://play.google.com/apps/testing/ninja.sesame.app.edge  
). Then go to Sesame Settings, Settings, Debug data, and "TAP TO SEND DEBUG DATA TO THE DEVELOPERS". Include the message "Contact actions".

That will give us a chance to see the problem and work on a fix.

Sorry for the hassle. Thanks for reporting and helping.

**Comment by ovc** [comment]
I also have aditional shourtcuts (call, mail and message) but without buying an addon. Their apears only in Nova's App search, but not in the Sesame app, and when I'm trying to press any of them I see an error "Unnable to open the shourtcut". Tried to fix any possible permissions issues, allowed everything without any luck.

**Comment by ghd182** [comment]
> Sorry about that. It's out fault. There's a bug in Contact Actions that we can't reproduce so we added some more debug data tracking to the Beta.
> 
> You can [join the Beta here](https://play.google.com/apps/testing/ninja.sesame.app.edge). Then go to Sesame Settings, Settings, Debug data, and "TAP TO SEND DEBUG DATA TO THE DEVELOPERS". Include the message "Contact actions".
> 
> That will give us a chance to see the problem and work on a fix.
> 
> Sorry for the hassle. Thanks for reporting and helping.

I'm on beta and I sent debug data as requested, hope to help 👍🏻

**Comment by philwall2** [comment]
Fixed.
