### ISSUE TITLE
Sesame is crashing in my device after latest update.

### ISSUE THREAD

**Issue by milindgoel15** [BranchMetrics/sesame_issues#144]
https://del.dog/pelonuphac
Here is the crash log.

Idk why it's happening. My device is nokia 6.1 with evolution X 3.5 if that helps.
I am using lawnchair V2 q pre alpha build 2599 and the issue started to happen after updating the sesame to its latest version.
I am beta tester of sesame if that helps too.

Lemme know if you require any more information.

**Comment by na51hog** [comment]
Apparently similar issue on S8+. I enter a couple of characters into the search widget and it crashes to the desktop

**Comment by milindgoel15** [comment]
Well, it doesn't even open here. I tap on search bar to open sesame and it just shows me blank screen there(aka crashed)

**Comment by Kordian-Dziwisz** [comment]
Same as @milindgoel15, cannot run sesame, Samsung S7(lineageos)+ nova launcher (problem appears when searching with sesame standalone and when searching with nova search with sesame integration)

**Comment by Kordian-Dziwisz** [comment]
@milindgoel15 reinstall helped

**Comment by milindgoel15** [comment]
Well, i even reflashed my rom and checked again. Same issue again
(I didn't reflashed just to check the issue, there was new build for my rom so had to do it) but didn't fixed the sesame crash for me

**Comment by philwall2** [comment]
Hey all. We should have a fix for this deploying in an hour or so. What happened is we're trying to figure out why #142 is breaking and we unintentionally created a conflict with the Recycler View. Thanks for reporting because we don't see the bug on our test devices (or hopefully we would have never pushed it to Beta :).

**Comment by milindgoel15** [comment]
It's working now thanks
