### ISSUE TITLE
Sesame contacts add on broken

### ISSUE THREAD

**Issue by dsouzadrian** [BranchMetrics/sesame_issues#146]
When I search for a contact, I don't see any results. The only result is from whatsapp.

**Comment by dsouzadrian** [comment]
I toggles hidden contacts and now I can find my contacts, but still no icons showing

**Comment by dsouzadrian** [comment]
![Screenshot_20191231-172945](https://user-images.githubusercontent.com/8682704/71636269-338ac080-2bf3-11ea-9631-5f7f7b047e7d.png)

**Comment by Kordian-Dziwisz** [comment]
Version? They fixed this issue in v 3.6.1
Check if contact actions add-on are enabled and permissions are given
[changelog](https://sesame.ninja/release_notes.txt)

**Comment by dsouzadrian** [comment]
Yup, its fixed. Thank you.
