### ISSUE TITLE
purchase not recognised

### ISSUE THREAD

**Issue by iamgimbo** [BranchMetrics/sesame_issues#149]
Hi.  I purchased sesame in October 2019, but the app doesn't recognise the purchase.  I have uninstalled and reinstalled the app, but this has not fixed the issue.  Please see screenshots of in app indicating no purchase and my Google play proof of purchase. Please advise on actions to fix. Thanks,
![Screenshot_2020-01-07-17-53-11-65](https://user-images.githubusercontent.com/59593590/71869806-49aafa80-3178-11ea-9810-436ad796061b.png)

**Comment by iamgimbo** [comment]
Sorry new to github. In app image to follow
![Screenshot_2020-01-07-17-52-38-79](https://user-images.githubusercontent.com/59593590/71869855-80811080-3178-11ea-9e78-d33b7417dc03.png)

**Comment by philwall2** [comment]
Hi, sorry about this. Google handles the purchase checks and often has errors. Try going to Sesame Settings > Settings > Purchases > and tap "REFRESH..."

Does that fix it?

**Comment by iamgimbo** [comment]
Hi.  Thanks for the reply.  I did try this and have tried it again, but it does not resolve the issue.

**Comment by philwall2** [comment]
Can you send me your Order ID # at phil@sesame.ninja? I can look it up and see what Google says the status is.

Have you double checked that you are using the same Google account that you purchased Sesame with?

----
Side note: What's sucks here is that Google handling all the purchases. So this is basically me trying to troubleshoot Google with you and my hands are mostly tied.

**Comment by iamgimbo** [comment]
Hi, I have managed to fix this.  I removed my second account from the phone and sesame then picked up my purchase on my primary Google account.  Just thought you should know in case anyone has similar issue in the future.  Thank you very much for your assistance.  Great customer service, it was really appreciate.  Cheers 👍

**Comment by philwall2** [comment]
Awesome. Glad you were able to sort it out!
