### ISSUE TITLE
crashing after latest beta update

### ISSUE THREAD

**Issue by hnmn** [BranchMetrics/sesame_issues#151]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/oxygen/oxygen:7.1.1/NMF26F/V11.0.2.0.NDDMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 18123, tid: 18123, name: sesame.app.edge  >>> ninja.sesame.app.edge <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'art/runtime/indirect_reference_table.cc:137] JNI ERROR (app bug): local reference table overflow (max=512)'
    x0   0000000000000000  x1   00000000000046cb  x2   0000000000000006  x3   0000000000000008
    x4   000000000000002d  x5   0000800000000000  x6   0000007fabd68000  x7   0000000000000000
    x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
    x12  ffffffffffffffff  x13  0000000000000000  x14  0000000000000000  x15  003a07cc057b9ec1
    x16  0000007fa8429ee0  x17  0000007fa83d3590  x18  0000000000000000  x19  0000007fabe1cb48
    x20  0000000000000006  x21  0000007fabe1caa0  x22  000000000000000d  x23  0000007fa7d86468
    x24  000000000000000a  x25  ffffffffffffffff  x26  000000000000151e  x27  0000007fe49f4721
    x28  0000007fa7dfc740  x29  0000007fe49f4620  x30  0000007fa83d0a20
    sp   0000007fe49f4600  pc   0000007fa83d3598  pstate 0000000060000000

backtrace:
    #00 pc 000000000006b598  /system/lib64/libc.so (tgkill+8)
    #01 pc 0000000000068a1c  /system/lib64/libc.so (pthread_kill+64)
    #02 pc 0000000000023f68  /system/lib64/libc.so (raise+24)
    #03 pc 000000000001c9ec  /system/lib64/libc.so (abort+52)
    #04 pc 0000000000431d74  /system/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+456)
    #05 pc 00000000000e5f0c  /system/lib64/libart.so (_ZN3art10LogMessageD2Ev+1576)
    #06 pc 000000000024d194  /system/lib64/libart.so (_ZN3art22IndirectReferenceTable3AddEjPNS_6mirror6ObjectE+308)
    #07 pc 000000000034d99c  /system/lib64/libart.so (_ZN3art3JNI21GetObjectArrayElementEP7_JNIEnvP13_jobjectArrayi+632)
    #08 pc 0000000000001964  /data/app/ninja.sesame.app.edge-1/lib/arm64/libnative-search.so (Java_ninja_sesame_app_edge_links_NativeSearch_setHaystack+388)
    #09 pc 0000000000400a68  /data/app/ninja.sesame.app.edge-1/oat/arm64/base.odex (offset 0x3ce000)

**Comment by philwall2** [comment]
Should be fixed now. Thanks for reporting.
