### ISSUE TITLE
Usage Access Permissions

### ISSUE THREAD

**Issue by JTFO4** [BranchMetrics/sesame_issues#153]
### Description

During setup, Sesame detects usage permissions activation inaccurately. Granting usage permissions for some other app triggers a confirmation in Sesame, even if Sesame was not granted usage permissions.

### Steps to Recreate
1. Install Sesame.
2. Follow the setup instructions until you reach Sesame's usage permissions activation.
3. Grant usage permissions for some other application (NOT Sesame).
4. Sesame will detect the permissions change for the other application, display confirmation that Sesame has been given usage permissions, and continue with the setup process despite not actually granting usage permissions to Sesame.

**Comment by philwall2** [comment]
Good catch. It's kind of difficult to detect what action happens on that screen. Perhaps the check we are using isn't sophisticated enough. Thanks for reporting, we'll take a look.
