### ISSUE TITLE
Search device contacts not working

### ISSUE THREAD

**Issue by thefyrehead** [BranchMetrics/sesame_issues#156]
Hello I open this issue on your Reddit account over a month ago and was told it was fixed and it was for a minute and then stopped working again.
![Screenshot_20200211-171722](https://user-images.githubusercontent.com/55513818/74294347-6b0c8280-4cf2-11ea-911e-594e634e5768.png)
![Screenshot_20200211-171714](https://user-images.githubusercontent.com/55513818/74294349-6c3daf80-4cf2-11ea-8694-5fa53e116986.png)

**Comment by philwall2** [comment]
Are you on a Saumsung? If so try going to Sesame Settings > Shortcuts > Contacts > and tap "Show hidden contacts"

Does that fix it?

**Comment by thefyrehead** [comment]
Yes. Thank you. Took 2 months to get that answer. I sort my contacts into
labels and them hide them from my contacts (like labeling and archiving
emails) and that is what is causing the issue. Maybe by default to display
my contacts and all labels? That would fix the problem and not show useless
data you are mntioning by enabling hidden contacts

**Comment by philwall2** [comment]
Sorry for the 2 month delay. I thought you had the same bug everyone else had. 

Anyways...  I'll keep this in mind for a future change but TBH it sounds like you're a bit of an edge case.
