### ISSUE TITLE
请问什么是接触式插件

### ISSUE THREAD

**Issue by nnoyuwan** [BranchMetrics/sesame_issues#161]
这个付费功能有什么用？

**Comment by philwall2** [comment]
如果您使用芝麻搜索并键入朋友的姓名，则会看到“短信，电子邮件和通话”图标。 使用“联系操作”，您可以添加和自定义10多个其他选项。 转到芝麻设置>设置>联系人操作，然后根据需要进行设置。
请注意，如果您使用的是Nova Launcher的App Search，则它们尚未更新为最新版本的Sesame，因此数据不会在那里显示。 您需要使用芝麻搜索（它也具有其他一些很酷的新功能）。
希望对您有所帮助。
