### ISSUE TITLE
Change name of shortcuts

### ISSUE THREAD

**Issue by HunterArmstrong** [BranchMetrics/sesame_issues#174]
In the app I hate how the shortcuts are named and feel that there should be a way to edit or change the name of a shortcut to something different or to just get rid of the app name the shortcut is coming from; and if the shortcuts are named the exact same name there should be a popup for the user to either rename a shortcut or leave them as is.

**Comment by philwall2** [comment]
Good idea. Also on roadmap already :)

**Comment by HunterArmstrong** [comment]
Also, feel free to look at issue 173. I think that was an issue you never really considered because it was difficult to to.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: philwall2 <notifications@github.com> Date: 3/31/20  09:39  (GMT-08:00) To: SesameCrew/sesame_issues <sesame_issues@noreply.github.com> Cc: HunterArmstrong <dhunterarmstrong@gmail.com>, Author <author@noreply.github.com> Subject: Re: [SesameCrew/sesame_issues] Change name of shortcuts (#174) 
Good idea. Also on roadmap already :)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SesameCrew/sesame_issues/issues/174#issuecomment-606740414",
"url": "https://github.com/SesameCrew/sesame_issues/issues/174#issuecomment-606740414",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
