### ISSUE TITLE
Can't change search engine for widget

### ISSUE THREAD

**Issue by d0x360** [BranchMetrics/sesame_issues#18]
I tried to set the widgets search engine to Bing but it just keeps using Google home.  I'm on Nova 6 and Android 8 on a Samsung note 9 (Verizon)

**Comment by philwall2** [comment]
How are you executing the Search? 

If you're hitting Enter on the keyboard, that's going to launch with the first QuickSearch app. By default that is set to the Google home. Go to Sesame Settings > Settings > Search Settings and drag Google down and pull up the browser/app you want.

If you're tapping on a suggestion, make sure you also set "Open search suggestions with" to "Search engine".

Does that fix it?

**Comment by d0x360** [comment]
I have the search engine set to Bing and and open search settings is set to search engine.

Do I need to download the separate Bing search app and if so why have Bing as a search engine option if it just uses Google anyways?  I'll download the Bing app and see if that fixes it.

Here is a screenshot of my current settings.  

Settings https://imgur.com/a/kuzhXzn

**Comment by philwall2** [comment]
You have the Google app in the #1 position. If you hit the enter key on your keyboard, it will launch that #1 app. 

Try moving Chrome into that #1 position.

**Comment by d0x360** [comment]
I downloaded the Bing search app and put it up top (wanna earn free Xbox money for searches) and that did the trick.

It's just a little confusing, I assumed because I set the search engine option to Bing it would open chrome and search with Bing.

It all works fine now, thanks for your help.  I think there needs to be some clarification in the app that if you want to change the search engine fully that you need to move the apps below the engine selection. 

Thanks for your help, much appreciated.
