### ISSUE TITLE
Feature request : Long pressed  shortcut to  add into app drawer

### ISSUE THREAD

**Issue by Amitkapadi** [BranchMetrics/sesame_issues#183]
Long press shortcut to add in app drawer like Chome webapp shortcuts. for example Twitter lite

**Comment by philwall2** [comment]
Can you explain a bit more? Do you want to be able to drag a shortcut from the long press menu onto the app drawer?

**Comment by Amitkapadi** [comment]
![20200419_121116](https://user-images.githubusercontent.com/3437446/79681388-88e8ed00-8237-11ea-9402-27da0b7707a9.jpg)



Yes, for example chrome sesame shortcuts we can add in app drawer.

Similar we can make Twitter  topic shortcuts.

Sesame whatsapp (perticular contact)app shortcuts to app drawer

**Comment by philwall2** [comment]
We're limited by what Android and the Launcher will let us do. Right now you can "Add to home" screen. But it's not possible for a 3rd party app to add things to the app drawer in the launcher.

Closing this because it's not possible.
