### ISSUE TITLE
Updates to Sesame

### ISSUE THREAD

**Issue by HunterArmstrong** [BranchMetrics/sesame_issues#187]
> Aight, we'll look at Castbox and other podcast apps.
> 
> We used to update all the time. Over the past year we've taken on some big projects that slowed down releases (UI options, building the data library for launchers, contact actions).
> 
> Right now we're working on another big feature (voice related). Once that comes out we're hoping to make a bunch of quick releases / improvements.

That was a reply from one of the devs when I had trouble with Castbox on sesame.

The only question I had was how do I know if there was something done or if my request was fufilled.

There isnt a website and the little "road map" they had never showed where they are at that time.

Is there a place I can go to see what's going on?

**Comment by philwall2** [comment]
The best place is in the release notes: https://sesame.ninja/release_notes.txt
