### ISSUE TITLE
Issue with Twitter shortcuts

### ISSUE THREAD

**Issue by Chiaomein** [BranchMetrics/sesame_issues#20]
Twitter shortcuts don't work. if i use my "New Message" shortcut, it just brings me up to the main home page instead of to my new messages screen

**Comment by philwall2** [comment]
It looks like this is a bug with Twitter. I switched to the Pixel Launcher and tested the New Message shortcut, it fails on that too.

Gonna close this issue but LMK if I might be wrong.
