### ISSUE TITLE
Nova app search integration: Long press on contact action does not work

### ISSUE THREAD

**Issue by oreineke** [BranchMetrics/sesame_issues#203]
How to reproduce:

0. Enable Nova Launcher Sesame integration
1. Bring up Nova Launcher's App Search
2. Enter a contact name
3. In the results list, long press on a contacts message, phone, or email icon

Expected behavior: The dialog to pick the preferred message number, email address or phone number appears

Actual behavior: The message, phone, or email icon disappears. A shortcut list (obviously from Nova Launcher, not from Sesame) appears, offering to "Edit" or "Remove" the "Shortcut".

**Comment by philwall2** [comment]
Nova Launcher hasn't implemented the latest version of Sesame's data library. They'd need to do that and update their long press UI.

FWIW the reason they're on a different version is they helped us develop the whole system. Later we found a faster way to do it, but that requires them to re-implement. I understand why they haven't chosen to do that yet.
