### ISSUE TITLE
Search engines icons are aligned to the left

### ISSUE THREAD

**Issue by Kordian-Dziwisz** [BranchMetrics/sesame_issues#211]
Search engines icons are aligned to the left,  You can see it on the screen when I tap one.

Is it a bug or a feature, because for me it's  a problem when I try to click It and accidentally click the one adjacent to the left.

**Comment by Kordian-Dziwisz** [comment]
See Google Maps icon
![Icons on the left side](https://i.imgur.com/Lz0nxoo.png)

**Comment by Martin5001** [comment]
Duplicate #204

**Comment by Kordian-Dziwisz** [comment]
@Martin5001 thanks, closing issue
