### ISSUE TITLE
Reddit login does not support 2FA

### ISSUE THREAD

**Issue by yochananmarqos** [BranchMetrics/sesame_issues#23]
I have the official Reddit app (for notifications in Joey) and Joey for Reddit installed. Joey is detected, but when the authorization page to login to Reddit appears, nothing happens after submitting my login info. It stays on the same page with my username filled in. I verified I'm using the correct password. Apparently whatever API you're using to login to Reddit is old and does not support 2FA.

Sesame 3.30-beta1
Android 9.0.0 / OxygenOS 9.0.4
T-Mobile OnePlus 6T

**Comment by philwall2** [comment]
@yochananmarqos as far as I can tell there's only the V1of the Reddit API and it doesn't support 2FA.

I could be wrong and we'd like to work with 2FA. Do you know any other apps that connect to Reddit and work when your 2FA is on?

If not, you can turn off 2FA, connect to Sesame, then turn 2FA back on.

**Comment by yochananmarqos** [comment]
Oh, I guess you're right. Their API doesn't support 2FA, I must've been thinking of something else. 
I disabled 2FA, authorized Sesame and re-enabled 2FA. I didn't think of that, thanks!

**Comment by pashynskykh** [comment]
> @yochananmarqos as far as I can tell there's only the V1of the Reddit API and it doesn't support 2FA. I could be wrong and we'd like to work with 2FA. Do you know any other apps that connect to Reddit and work when your 2FA is on?

Sync for Reddit works well with 2FA enabled. If you have problems with it, maybe you'll try contact u/ljdawson, the developer of Sync for Reddit?

**Comment by alien2003** [comment]
I guess it's a built-in browser issue
