### ISSUE TITLE
Add a button to open Google assistant

### ISSUE THREAD

**Issue by MatteCarra** [BranchMetrics/sesame_issues#26]
LawnChair has this feature in the default search bar.
It would be awesome to have it also when using sesame.

**Comment by skittles9823** [comment]
This is more so a feature request for Lawnchair I suppose?

**Comment by MatteCarra** [comment]
You are right.
I thought that Sesame was responsible of the design of the search bars, but I've noticed it's handled by LawnChair.
Sorry

**Comment by MatteCarra** [comment]
I've contacted LawnChair devs and they said that you should implement a default assistant to make the button visible in their bars:
![Screenshot_20190321-170010](https://user-images.githubusercontent.com/11074527/54766142-130cef00-4bfb-11e9-94f4-6fc30ac970b2.jpg)

I hope it helps.

**Comment by philwall2** [comment]
Yep, we can add this. Let me talk to Steve. It might be something we can get in our next 2 releases.

**Comment by philwall2** [comment]
Completed in last release.
