### ISSUE TITLE
Quick toggle for common settings (Airplane Mode, Bluetooth, etc.)

### ISSUE THREAD

**Issue by philwall2** [BranchMetrics/sesame_issues#29]
Not sure how possible this is without asking for dangerous permissions. But it'd be cool. Let us know what other actions you'd like to be able to trigger directly from Sesame.

**Comment by skittles9823** [comment]
Pretty sure Sesame would need the `android.permission.WRITE_SECURE_SETTINGS` permission, which can only be granted with adb or root for these kinds of toggles.
