### ISSUE TITLE
feature request add support for retro music in quick search

### ISSUE THREAD

**Issue by shafschwd** [BranchMetrics/sesame_issues#35]
add support for retro music in quick search to search music quickly

playstore link 👇 

https://play.google.com/store/apps/details?id=code.name.monkey.retromusic

**Comment by philwall2** [comment]
Sure, we can take a look. Not sure if it's possible yet, Retro Music will need to support opening search URLs.

I added it to our list in #7 and am closing this as a duplicate. Thanks for the good request!
