### ISSUE TITLE
Installing apk files not working

### ISSUE THREAD

**Issue by milindgoel15** [BranchMetrics/sesame_issues#37]
Hi there, there's a issue with opening files from the storage. For example if we want to open apk files and install directly from the search box, it doesn't do anything and just simply gets closed. Is this issue known. Please fix this.

**Comment by philwall2** [comment]
We could be mishandling .apks. We're using a basic view intent with a built in MIME type detection and hoping the app handles it properly. What app is associated with your files? AKA are you using a 3rd party file manager, if so what is it?

The more detail you provide, the better.

**Comment by milindgoel15** [comment]
I am using Solid Explorer(latest beta) btw. 
Does the file manager is directly link to accessing device files aka apk files to install them by sesame?

**Comment by philwall2** [comment]
Sesame is sending the intent to Android, who is then routing it to Solid Explorer. Solid Explorer is normally pretty good about opening stuff.

We looked at stackoverflow and on the surface it looks like we're doing this right. We could play around with the details and see if it starts working though. Thanks for letting us know.

**Comment by milindgoel15** [comment]
Nice thanks. I will be waiting for the update.

**Comment by bebotette** [comment]
have the same issue. searched for an apk, tapped on it, then nothing happens. no preview of apk also.

**Comment by milindgoel15** [comment]
I forgot about this and it seems that this bug is not fixed yet. Coz u didn't changed the label

**Comment by milindgoel15** [comment]
Also, it seems that with updates after this issue, i can no longer try to get apk files in search results or maybe my settings are incorrect.

**Comment by philwall2** [comment]
We haven't changed anything. It's still on the todo list to investigate. We're working on a new big feature now. That'll take a few weeks. After that we're going back to the todo list. But as you can see, it's quite long :)

**Comment by milindgoel15** [comment]
Oh that's nice.

**Comment by milindgoel15** [comment]
Development abandoned or just stopped for break?
