### ISSUE TITLE
Subscribed subreddits for RIF are picked up as ESPN shortcuts

### ISSUE THREAD

**Issue by draguindin** [BranchMetrics/sesame_issues#45]
The subreddits I subscribe to are duplicated in the shortcut menu with both the Reddit is Fun shortcut as well as an ESPN shortcut which is invalid. For example, when typing "soccer" in Sesame, I get a result for "Reddit is fun: /r/soccer/" and another labeled "ESPN: /r/soccer/"

**Comment by draguindin** [comment]
When selecting the ESPN result I get a system error, "Unable to open shortcut"

**Comment by philwall2** [comment]
Well this one's kind of funny :)

The way our Reddit detection works is we send out a "can anyone open this reddit link". I guess either ESPN said "yes" at one point or some wires got crossed. 

Try going to Sesame Settings > Permissions > and toggle off/delete the Reddit OAuth. Check to see the ESPN shortcuts are gone, then reconnect to Reddit. Should fix it.

**Comment by draguindin** [comment]
Hm, so I turned off Reddit oauth then tried accessing the shortcut but the
ESPN shortcut persisted. I also tried disabling then reenabling with the
same result. Any other ideas?


Thanks,

Diego

**Comment by philwall2** [comment]
Sorry about that. This is our bug but there's not a good solution. You have
4 options. First, check in Sesame Settings > Permissions > Reddit and see
if the ESPN app is listed there as a reddit app. If it's not, do option #2.
If it is, your best bet is option #1

Options:

   1. Turn OFF the shortcuts in Sesame Settings > Shortcuts > ESPN
   2. Uninstall the ESPN app, open Sesame Settings to trigger a refresh.
   Sesame will delete the shortcuts for ESPN, and you can reinstall
   3. Reset all your Sesame data
   4. Make a backup of the data from Sesame Settings > Settings > Backup &
   restore, then send us the .sesame backup file. We'd clean it up for you and
   sent it back to you. Then you could restore from they file

Again, sorry for the inconvenience.

Phil

**Comment by draguindin** [comment]
Hey, Phil,

Realizing that I don't use the ESPN app I simply uninstalled it and stopped
at step 2 (though I also didn't want to deal with exporting the data to be
manually adjusted then reimporting it as I didn't want to risk any further
and unanticipated issues).

Thanks for the assistance!


-Diego

**Comment by philwall2** [comment]
Cool. Glad it worked out. Feel free to hit me up anytime with feature ideas
etc.

**Comment by gofirst2220** [comment]
It still happens to me but with few other apps like Discovery Go and Adult Swim and even ESPN app. And I even follow your instructions but it still happens to me
