### ISSUE TITLE
Shortcuts icons are not appearing

### ISSUE THREAD

**Issue by rodrigoswz** [BranchMetrics/sesame_issues#47]
Since the latest beta updates (hyperion and lawnchair support), the shortcuts icons by sesame are not appearing in my launcher or even in Sesame settings. 

Here some samples:

![Instagram shortcuts without icons](https://i.imgur.com/BRkSJwb.png)

![Sesame settings for Instagram, no icons too](https://i.imgur.com/UBlTWDb.png)

I'm using Hyperion at moment, but the same problem happens on Lawnchair v2.

**Comment by philwall2** [comment]
Hey @rodrigoswz . It's hard to say what's breaking here. The star icon is a failure state, so at some place the data isn't getting across to Sesame. 

Steve and I tested on our devices and the icons are showing for Hyperion and Lawnchair. Since this seems localized to your device, your best bet is try refreshing Sesame data and rebooting.

If that doesn't work; what's your Android Version and Device?

**Comment by rodrigoswz** [comment]
Hey @philwall2, what's you mean with "refreshing sesame data and rebooting"? If it's to force refresh shortcuts data and reboot my phone, then that's don't works for me, I've tried it many times.

Or I need try clean data/reinstall sesame? **EDIT: I just tried this, unfortunately it did not solve anything.**

My device is an OnePlus 3T running Android 9.0.

**Comment by philwall2** [comment]
Yeah @rodrigoswz I meant the thing you've tried many times.

Hmm... really not sure what this bug could be. Would you mind sending us debug data and include the message "It's Rodrigo and my icons aren't displaying"?

**Comment by rodrigoswz** [comment]
@philwall2 done! Weird... I did not think that this bug was so unknown, I see this problem in screenshots by another users in telegram groups of lawnchair and hyperion.

**Comment by rodrigoswz** [comment]
Hey @philwall2 I installed Nova Launcher and got the icons back on Lawnchair and Hyperion!  Apparently the icons are gone if I do not have Nova Launcher installed 🤔

**Comment by philwall2** [comment]
Hey @rodrigoswz this is a good clue but I uninstalled Nova Launcher and still see the icons. I rebooted, refreshed data etc, still see them.

Steve looked at your debug data from before. He told me "His icon URIs are just null. They shouldn't those icons come with Sesame. Not sure why some copies of Sesame can't find the vector icons that we put in the APK."

So unfortunately we're still kind of stuck. I'll see if the Nova trick works for him.

**Comment by philwall2** [comment]
@rodrigoswz update: we use a different method for handling icons with Nova vs Hyperion/Lawnchair. We have a check in place to see "should we do it the Nova way?". There might be a bug in this code causing the problem you're seeing.

Thanks a bunch for letting us know and finding the Nova clue! You debugged this :)

We're going to push a fix to Beta in a little bit. Let us know if it worked.

**Comment by stevehb** [comment]
@rodrigoswz Just deployed 3.4.0-beta3 to the beta channel. I think this will fix the icon issue.

**Comment by rodrigoswz** [comment]
The new beta update with the fix works perfectly for me, thank you for the attention and amazing support @philwall2 @stevehb !

**Comment by philwall2** [comment]
No problem. Thanks for helping us catch bugs.
