### ISSUE TITLE
Integrated launcher bug

### ISSUE THREAD

**Issue by RikKoedoot** [BranchMetrics/sesame_issues#52]
I am using lawnchair v2.0-2047 (internal dev build) and I've noticed that when I try to pin a shortcut for Gmail or Google calendar that I'm not capable of doing this, due to no detected integrated launcher, tho for other apps like Google fit or SoundCloud it does allow me to pin shortcuts. In the attached screenshot you can see the issue.
![Screenshot_20190502-212440](https://user-images.githubusercontent.com/29402532/57101129-dd424680-6d20-11e9-9cb2-b1e955bb6dae.png)
![Screenshot_20190502-212139](https://user-images.githubusercontent.com/29402532/57101131-dd424680-6d20-11e9-8d3c-46a5f42160c2.png)
![Screenshot_20190502-212129](https://user-images.githubusercontent.com/29402532/57101132-dd424680-6d20-11e9-8a77-f393c8ff0f1f.png)
![Screenshot_20190502-212623](https://user-images.githubusercontent.com/29402532/57101208-fea33280-6d20-11e9-90cb-c420f70134eb.png)

**Comment by philwall2** [comment]
@rickkode great catch. Fixed it. Should be out in the next release.
