### ISSUE TITLE
SIimple mode

### ISSUE THREAD

**Issue by infinit7even** [BranchMetrics/sesame_issues#53]
Add the ability to disable all shortcuts for those who just want to have the search function between the apps
![Screenshot_20190504-155345_Sesame](https://user-images.githubusercontent.com/50268291/57180045-e77d5580-6e84-11e9-856a-ae16bb16bf15.jpg)

**Comment by philwall2** [comment]
You mean you only want app results? No shortcuts at all?

**Comment by infinit7even** [comment]
Yes!

very similar to this screenshot where only applications appear without
shortcuts

obviously the applications on only one Rigo very large

the results for the Web appear at most under the application icons

**Comment by infinit7even** [comment]
This is a possible idea of ​​the result

![Screenshot_20190506-194425_Finder](https://user-images.githubusercontent.com/50268291/57244560-fb69b880-7038-11e9-9edb-3f04eb2913f7.jpg)

**Comment by philwall2** [comment]
Thanks for explaining. Sesame's whole deal is shortcuts, so it's a bit of an unexpected request. But that just means it's not how *we* think of the app. I'll consider this for #40 and will close this out since all UI requests are going in #40.
