### ISSUE TITLE
Single icon graphic

### ISSUE THREAD

**Issue by infinit7even** [BranchMetrics/sesame_issues#54]
Add the ability to decide an application-specific graphic even when an icon pack is in use

![Screenshot_20190506-195021_Nova Launcher](https://user-images.githubusercontent.com/50268291/57244258-5058ff00-7038-11e9-9987-7fec0f2514e4.jpg)

**Comment by infinit7even** [comment]
This is an example of when an icon is not supported by the Icon Pack

![Screenshot_20190506-195352_Sesame](https://user-images.githubusercontent.com/50268291/57244515-d37a5500-7038-11e9-868c-f82f5425b0d8.jpg)

**Comment by philwall2** [comment]
Yep, for sure a good idea. We've got that on #40 so I'm going to close this as a duplicate. But I'm loving the good feedback!

BTW, we just did a pretty big UI release so we're going to get back to building cool shortcuts/data features for a while. But we'll be back for the UI options :)
