### ISSUE TITLE
Can we support swipe down gesture to close sesame?

### ISSUE THREAD

**Issue by dcai** [BranchMetrics/sesame_issues#59]
So can close sesame quickly.

**Comment by philwall2** [comment]
Possibly but help me understand. Swipe down from where? If you swipe on the list that should scroll, keyboard should close keyboard.

Is there an app that has "swipe to close" that I should check out?

Also, just for arguments sake, isn't it easy to use the back button to close it?

**Comment by ghillb** [comment]
> Swipe down from where?

When you are at the top of the list. This would be consistent with some launchers (eg Nova has this gesture in the app drawer).

**Comment by philwall2** [comment]
K. We'll consider this for #40. Closing this issue as a duplicate.
