### ISSUE TITLE
Feature : Yatse quick search

### ISSUE THREAD

**Issue by ghost** [BranchMetrics/sesame_issues#60]
Would love to see Yatse as a quick search option, particularly for (search:all)

I've contacted their devs, and they said they aleady have it exposed as a search provider, but I'm not sure what else is necessary to get it into the quick search application list

**Comment by philwall2** [comment]
Sure. Is [this](https://play.google.com/store/apps/details?id=org.leetzone.android.yatsewidgetfree) the app? 

If so, did they mention how search is exposed? We'd need a URL or parameter we could pass things off to. 

E.g.
>  adb shell am start \
>    -n com.packagename/.android.ui.main.MainActivity \
>    -e com.packagename.intent.extra.QUERY_STRING "search\ query"
>
> Component name is "com.packagename/.android.ui.main.MainActivity".
> Extra (string) key is "com.packagename.intent.extra.QUERY_STRING".

**Comment by Tolriq** [comment]
Yatse either provide an Android default provider as ```org.leetzone.android.yatsewidget.provider.SearchProvider``` or expose a standard 

```
<activity
            android:name="org.leetzone.android.yatsewidget.ui.GlobalSearchActivity"
            android:exported="true">
<intent-filter>
                <action android:name="com.google.android.gms.actions.SEARCH_ACTION" />

                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>`
```

All easily borrowed from the manifest and default Android ways.

**Comment by ghost** [comment]
@philwall2 yes, that is the correct application, and the commenter who just posted appears to be the dev/maintainer I spoke to on their forums

**Comment by philwall2** [comment]
Thanks @hookshot1  and @Tolriq . We'll add this when we do #7 , which shouldn't be too long from now.
