### ISSUE TITLE
Request: ability to only have contacts and not recent shortcuts in the search menu

### ISSUE THREAD

**Issue by Scerball** [BranchMetrics/sesame_issues#61]
I'd like to just have contacts there. No shortcuts.

**Comment by philwall2** [comment]
We have these controls now. Go to Sesame Settings > Shortcuts > open each app and toggle OFF all  shortcuts. It'll be tedious to set up, but Contacts is 1 of 100 types of shortcuts Sesame makes. If you really want only Contacts it's doable :)

**Comment by Scerball** [comment]
Yes I see that. But what I would like is having the shortcuts ONLY show
when I search for them. I don't want them in my contacts list. This feature
is not implemented.

**Comment by philwall2** [comment]
Sorry, I might be confused. What do you mean by "contacts list"?

It sounds like you might be asking to not have any shortcuts show until you start typing the search. In other words you don't want the list of recent shortcuts. Is that right?

**Comment by Scerball** [comment]
Sorry for the late reply. But yes I'd like to not see recent shortcuts.
