### ISSUE TITLE
support for gmail label:unread

### ISSUE THREAD

**Issue by bebotette** [BranchMetrics/sesame_issues#62]
I always check mail using the search bar for gmail and with the entry:
label:unread
and it shows me all the unread messages, regardless the label.
Right now, when I try to add a new shortcut for gmail, there's no support for that. It only supports currently existing labels inside my gmail.
I hope sesame allows manual inputs like this. ty

**Comment by philwall2** [comment]
Hi. This is a known issue. Gmail changed how they handle creating shortcuts. We need to find a new solution to work with their change. I'll up the priority. Closing as duplicate to #32
