### ISSUE TITLE
Device files Features Request

### ISSUE THREAD

**Issue by bebotette** [BranchMetrics/sesame_issues#63]
One primary use of my sesame integration is searching for files inside my device storage or sd card. And it does this fantastically. But it only searches and that's all sesame can do.
I'd like options please:
1. quick option to locate file using preferred explorer app like Solid Explorer. Probably a context menu after long press? 
2. Show file icons properly. If it's a PDF, show pdf icon, etc.
3. support for directly installing APKs
4. android share button (for quickly sending or sharing that particular file).

Thank you.

**Comment by philwall2** [comment]
Hey @bebotette , good ideas.

1. Can you describe the use case a bit more? Right now Sesame uses whatever your default file manager is. Sounds like you want to choose each time which file manager is used. If that's right then it's probably a pretty low priority unless you can help me understand the use case.

2. We should be using the icons given to us by the system. For example I do see .pdf icons. Can you tell me which ones are not how you'd hope? Then I can see about improving them.

3. Yep, we've got this on #37 

4. Good idea. Perhaps we can add that as an action associated with files and make it available on long press in Search?

**Comment by philwall2** [comment]
Closing since 3 & 4 are covered and no reply from OP on 1 & 2.

**Comment by bebotette** [comment]
sorry I lost track of this thread. Hopefully I could get it back.
1. for instance, if I search for a pdf, or an apk, I'd like to see probably an added option in context menu (after long press) or an icon to the right of it for me to quickly locate the file in my file explorer of choice. upon tapping, this will open my file explorer (I'm using solid explorer) and highlight the object I'm looking for.
2. I'm sorry but icons don't really work well on my end. If I search for a pdf, it doesn't show a pdf icon. it only shows a default generic file icon. Same goes with apk files.
3. Did you already update the app with this feature? Because I tried and still nothing happens when I click on an apk file
4. A long press would be nice, like an extra option in context menu.

Perhaps I'd like to rephrase the majority of my requests: maybe you can add extra options to the context menu instead? Currently when I long press an item, there are only three options: 'add to home,' 'shortcut options', and 'hide.' Maybe we can add 'locate file in file explorer', 'share,' etc.

Thank you for looking into these. thanks for your time and effort. Cheers.
