### ISSUE TITLE
Default Search option malfunctioning

### ISSUE THREAD

**Issue by killshot13** [BranchMetrics/sesame_issues#65]
Was defaulting to Bing instead of DuckDuckGo. Manually input URL in custom bar and rec'd invalid error msg. Switched back and Sesame chose YouTube instead. Now stuck on YouTube for all options.

**Comment by philwall2** [comment]
That sounds annoying. Can you send me a screenshot of your settings? There's probably an easy fix here, the more detail you provide the better.

**Comment by killshot13** [comment]
Yes Sir. Shall I send them here or post to GitHub+

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by philwall2** [comment]
You can post them in this thread. If you don't want other ppl to see you can email me instead: phil@sesame.ninja

**Comment by killshot13** [comment]
I have them edited for privacy. Here you go!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by philwall2** [comment]
@killshot13 I don't see them. Am I missing something?

**Comment by killshot13** [comment]
I sent them to the SesameCrew email

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by philwall2** [comment]
Resolved with user via email.
