### ISSUE TITLE
Resizable homescreen widget

### ISSUE THREAD

**Issue by 8bitPit** [BranchMetrics/sesame_issues#66]
I would like to have an option to change the widget’s width on any launcher. I think you set the widget’s resize mode to “[RESIZE_HORIZONTAL](https://developer.android.com/reference/android/appwidget/AppWidgetProviderInfo.html#RESIZE_HORIZONTAL)“, but afaik, some third party launchers like Nova launcher ignore the flag, which gives you inconsistent behavior on different launchers.

**Comment by philwall2** [comment]
Hey, what's the desired behavior you're looking for?

**Comment by 8bitPit** [comment]
I would prefer that the widget can be rescaled on any launchers. For example, here's a gif I made on Google's Pixel launcher (version 10). It could also have something to do with the "[minResizeWidth](https://developer.android.com/reference/android/appwidget/AppWidgetProviderInfo.html#minResizeWidth)", because it seems your widget could be resized horizontally, seen by the resize handles that appear on a long press.

![ezgif com-crop](https://user-images.githubusercontent.com/9284845/58309449-89e58480-7e04-11e9-9b9a-b90fcc075bda.gif)

**Comment by philwall2** [comment]
Ah, gotcha. Thanks for explaining.

**Comment by philwall2** [comment]
Update: Steve fixed this, should be in the next version!

**Comment by 8bitPit** [comment]
Great :D
