### ISSUE TITLE
An easier way to create url shortcuts (bookmarks)

### ISSUE THREAD

**Issue by natkey** [BranchMetrics/sesame_issues#69]
Since most browsers have url shortcuts, I think it would be nice to be able to import many bookmarks at once rather than having to enter one at a time. E.g chrome bookmarks can be exported (from the desktop version) as a html file. These can then be imported all at once into sesame and used as shortcuts for, say chrome (or any other browser) on the mobile phone. Just the same way you don't have to manually enter every contact name for an app like WhatsApp.

**Comment by philwall2** [comment]
Good idea. I'll talk to Steve and see how easy this would be to implement. Thanks!

**Comment by philwall2** [comment]
Hey @natkey , bad news... we looked into this and it seems [Google removed this ability](https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-bookmark-browser) in Android 6.

Sorry about that.

**Comment by natkey** [comment]
@philwall2 Thank you for your reply. Actually, I do understand that android imposes this limitation. It is not what I was requesting for. What I meant was to import the urls from an html file which you can easily obtain from a chrome **desktop** browser (which a lot of people sync with the mobile browser anyway). You can export bookmarks from many desktop browsers as a html file. That's why I talked about the desktop version. It's just an html file. So I would imagine it's possible for sesame to extract all the bookmark urls from it. This would make life so much easier than having to type 1 url at a time until you get them all in.
