### ISSUE TITLE
Can't connect telegram

### ISSUE THREAD

**Issue by koorool** [BranchMetrics/sesame_issues#73]
I have troubles connecting telegram account.

1. Enter number and tap 'send code' 
First time I always receive an error "Telegram is unable send code bla bla bla" 
2. Tap again (always second time). 
Code is sent! 
3. Enter code. 
Wrong. 

Goto 1.

Have this issue for a while.

**Comment by philwall2** [comment]
Do you have 2FA on? If so, try turning that off.

**Comment by koorool** [comment]
Disabling 2FA actually fixes 3 point. You can reenable it again once telegram is connected. 
Thought, I have to tap "Send code" two times anyway.

All of this still sounds like a problem to be fixed :)

**Comment by philwall2** [comment]
We'd be open to fixing it, but I think this is actually 100% on Telegram. Last time we looked into it (2 months ago), their API didn't have a way for 3rd party apps to work with their 2FA.

And the sending, receiving, and verification of codes is all Telegram too.

Gonna close this for now, but if you can find any information that says this is something we can fix, we'd be happy to do it.

**Comment by blueset** [comment]
Also having the same issue.

I'm not sure which implementation of MTProto are you using, but Telegram did provide interfaces to log in with 2FA.

Sample code with TDLib implementation of 2FA in Java can be found here: https://github.com/tdlib/td/blob/21dee3b1d923f3fdacc711b46ad102b1d0d1439b/example/java/org/drinkless/tdlib/example/Example.java#L86

**Comment by philwall2** [comment]
Thanks! I'll talk to Steve about it. I know he looked at Telegram 2FA 6 months ago and it wasn't doable. This may be what we were missing!

**Comment by edshamis** [comment]
Any news?))
