### ISSUE TITLE
Inconsistency with pinned shortcuts order

### ISSUE THREAD

**Issue by mxng** [BranchMetrics/sesame_issues#78]
Pinned shortcuts order is shown reversed in Nova Launcher.

For example, order of shortcuts set in Sesame settings is 1, 2, 3 from top to bottom. But when holding the app icon and the popup pops out, the order of the shortcuts is 3, 2, 1 from top to bottom.

**Comment by philwall2** [comment]
Good catch. Nova controls the ordering on their end. Only they can fix it

**Comment by CliffWade** [comment]
This is because Nova Launcher follows what Pixel Launcher does and orders shortcuts to be closest to your thumb due to the popup window opening in either direction(top or bottom) of the screen.
