### ISSUE TITLE
Can't sign into Reddit with 2 factor authentication

### ISSUE THREAD

**Issue by BurnerWah** [BranchMetrics/sesame_issues#89]
There are two issues here. 

1. Sesame doesn't stay in the recents list, so switching to another app to get a 2FA code makes it really hard to sign in. 
2. Hitting reddit's log in button doesn't go to 2 factor authentication. If you put in the wrong password it says it's the wrong password, but putting the right password in does nothing. 

Running version 3.5.2.

**Comment by philwall2** [comment]
Agreed on the Recents list. That is annoying for signing into stuff. But if we had Sesame appear in Recents, it'd show up every time you use a shortcut. We figured that'd be annoying. Thoughts?

Re: 2FA, Reddit straight up doesn't support 3rd party apps oauth if 2FA is on. At least that was the case 4 months ago when we last checked.

You just need to turn off 2FA temporarily, oauth with Sesame, then turn it back on.
