### ISSUE TITLE
Use Google Voice as SMS app

### ISSUE THREAD

**Issue by squarepegsys** [BranchMetrics/sesame_issues#94]
Very new user to Sesame but a long time Voice user.

When I search and find a contact and click the SMS icon, it lists me choices to send an SMS with, but not Voice (my preference)

**Comment by philwall2** [comment]
Hi @squarepegsys When you tap on the SMS icon, Sesame is handing that request over to the the Android System. So unfortunately it's Android that's not giving you the option to send an SMS with Voice. This likely means Voice isn't registered as an SMS app.
