### ISSUE TITLE
Iconpack masking and adaptive icons 

### ISSUE THREAD

**Issue by RikKoedoot** [BranchMetrics/sesame_issues#97]
I wanted to give an idea for some improvements, with sync icons with lawnchair, would it be possible to use custom set icons? Also is it possible to get iconpack masking for non supported icons, and another nice integration with lawnchair customization sync, it would be nice to have adaptive icon sync, maybe you could be able to make a separate option for it aswell in sesame settings so other launchers users can enjoy it too
I hope this helps you guys improve sesame

**Comment by philwall2** [comment]
Hey @rickkode great ideas. I think we've got some of this covered and other things we can look at when we do more UI work in#40.

Right now you should be able to use custom icon packs. We've made all our customization data available to the launchers via the integration. In general, we're hoping they handle most of the icon stuff. That's their specialty.

FWIW we're working on some new data features. That's kind of our specialty :)
