### ISSUE TITLE
Includes sentence to be translated and update translation of pt_BR.

### ISSUE THREAD

**Issue by GabrielMGitHub** [BranchMetrics/sesame_issues#99]
Please include sentence for translation and update language pt_BR in the app, I made several corrections several months ago and were not updated in the app.

![Screenshot_20190810-035202_Sesame](https://user-images.githubusercontent.com/8754997/62818787-a13e2f00-bb22-11e9-8049-63bb099a1ee4.jpg)

**Comment by philwall2** [comment]
@GabrielMGitHub we pulled in the latest translations in the new Beta (3.5.3 beta 3). Thanks for your help!
